// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Samples.TexturedCube
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f02000a
			public const int action_bar = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int action_text_color = 2130837515;
			
			// aapt resource value: 0x7f020006
			public const int focused = 2130837510;
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020008
			public const int list_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int list_text_color = 2130837513;
			
			// aapt resource value: 0x7f020007
			public const int selected = 2130837511;
			
			// aapt resource value: 0x7f020001
			public const int steel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int stone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int translucent = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int water = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int wood = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int hidecontainer = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int menuSwitchTextures = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int paintingview = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int switch_texture = 2131165186;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int cube_edit_bar = 2131099648;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int hide = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int show = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int switch_texture = 2130968577;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int SMSActionBar = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_ActionLight = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
